// crates/spacegame2d/hud/src/components/StateDot.svelte
<script lang="ts">
  let {
    tone,
    certainty = 'confirmed',
    size = 6,
  }: {
    tone: 'friendly' | 'enemy' | 'neutral';
    certainty?: 'confirmed' | 'estimated' | 'stale';
    size?: number;
  } = $props();
</script>

<i
  class={tone}
  class:estimated={certainty === 'estimated'}
  class:stale={certainty === 'stale'}
  style:width={`${size}px`}
  style:height={`${size}px`}
  aria-hidden="true"
></i>

<style>
  i {
    display: inline-block;
    flex: none;
    border: 1px solid currentColor;
    border-radius: 999px;
    background: currentColor;
  }
  .friendly { color: var(--cyan-500); }
  .enemy { color: var(--coral-500); }
  .neutral { color: var(--gray-300); }
  .estimated { border-style: dashed; background: transparent; }
  .stale { background: transparent; opacity: .5; }
</style>

// ui/Fleet Design System/components/signals/StateDot.jsx
import React from 'react';

/** 6px allegiance dot. Hollow = unconfirmed, dashed = estimated. */
export function StateDot({ tone = 'neutral', certainty = 'confirmed', size = 6, style }) {
  const c = { friendly: 'var(--sig-friendly)', enemy: 'var(--sig-enemy)', neutral: 'var(--sig-neutral)' }[tone];
  const border = certainty === 'estimated' ? '1px dashed ' + c : '1px solid ' + c;
  return <i style={{ display: 'inline-block', width: size, height: size, borderRadius: 'var(--r-full)', border, background: certainty === 'confirmed' ? c : 'transparent', opacity: certainty === 'stale' ? 0.5 : 1, ...style }} />;
}
